FactorioItemBrowser\CombinationApi\Client\Transfer\Combination:
  exclusion_policy: all
  properties:
    id:
      type: string
    shortId:
      type: string
    modNames:
      type: array<string>
    isDataAvailable:
      type: boolean
    exportTime:
      type: DateTimeInterface<'Y-m-d\TH:i:sP'>
