FactorioItemBrowser\CombinationApi\Client\Transfer\Job:
  exclusion_policy: all
  properties:
    id:
      type: string
    combinationId:
      type: string
    status:
      type: string
    priority:
      type: string
    errorMessage:
      type: string
    creationTime:
      type: DateTimeImmutable<'c'>
    changes:
      type: array<FactorioItemBrowser\CombinationApi\Client\Transfer\JobChange>
