FactorioItemBrowser\CombinationApi\Client\Transfer\JobChange:
  exclusion_policy: all
  properties:
    initiator:
      type: string
    status:
      type: string
    timestamp:
      type: DateTimeInterface<'Y-m-d\TH:i:sP'>
